#!/usr/bin/env node
// PreToolUse hook for Claude Code, wired via claude-settings.json (generated by
// agent/worker.mjs). Blocks Edit/Write/MultiEdit calls that touch a file
// outside agent/lib/allowlist.mjs's ALLOWED_FILES.
//
// Contract (docs/AGENT_CONTRACT.md): reads the hook event JSON from stdin,
// resolves tool_input.file_path (or MultiEdit's file_path) against the event's
// cwd (or AGENT_DEV_DIR/web from env, or process.cwd() as last resort), and
// exits 2 with a Spanish reason on stderr if the path is not allowed. Exit 0
// otherwise. Any parse/read error is treated as a violation (fail closed).

import { isAllowed } from '../lib/allowlist.mjs';
import path from 'node:path';

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) {
    chunks.push(chunk);
  }
  return Buffer.concat(chunks).toString('utf8');
}

function resolveWebDir(event) {
  const envDevDir = process.env.AGENT_DEV_DIR?.trim();
  if (envDevDir) return path.join(envDevDir, 'web');
  if (event && typeof event.cwd === 'string' && event.cwd) return event.cwd;
  return process.cwd();
}

function extractFilePaths(event) {
  const input = event?.tool_input;
  if (!input || typeof input !== 'object') return [];
  const paths = [];
  if (typeof input.file_path === 'string') paths.push(input.file_path);
  // MultiEdit uses the same top-level file_path as Edit; some tool variants
  // may nest per-edit paths, so scan for any additional string file_path-like
  // fields defensively (harmless no-op if absent).
  if (Array.isArray(input.edits)) {
    for (const edit of input.edits) {
      if (edit && typeof edit.file_path === 'string') paths.push(edit.file_path);
    }
  }
  return paths;
}

async function main() {
  let event;
  try {
    const raw = await readStdin();
    event = JSON.parse(raw);
  } catch {
    process.stderr.write('No se pudo interpretar el evento del hook; se bloquea por seguridad.\n');
    process.exit(2);
    return;
  }

  try {
    const webDir = resolveWebDir(event);
    const filePaths = extractFilePaths(event);

    if (filePaths.length === 0) {
      // Nothing to check (e.g. tool without a file_path); allow.
      process.exit(0);
      return;
    }

    for (const filePath of filePaths) {
      if (!isAllowed(filePath, webDir)) {
        process.stderr.write(
          `Archivo no permitido: "${filePath}". Solo se puede editar el contenido de texto y estructura ` +
            'de la landing incluido en la lista blanca (src/data/content.es.ts, content.en.ts, ' +
            'platform-copy.ts, models-copy.ts, y los archivos del theme v1-nature-distilled: copy.ts, ' +
            'tokens.css, Page.astro). No se hizo ningún cambio.\n',
        );
        process.exit(2);
        return;
      }
    }

    process.exit(0);
  } catch {
    process.stderr.write('Error al validar la lista blanca; se bloquea por seguridad.\n');
    process.exit(2);
  }
}

main();
